### ISSUE TITLE
check_network_device_ping bad interpreter

### ISSUE THREAD

**Issue by aloudahi** [incubusbatanga/nagios-plugins#1]
-bash: ./check_network_device_ping.pl: /usr/bin/perl^M: bad interpreter: No such file or directory

**Comment by markomdinic** [comment]
Common path for perl binary is /usr/bin/perl.

You either have perl installed in some other location or don't have perl installed at all.

Please make sure you have a working installation of perl with all required modules before running the script. Most modules this script uses are a part of perl base distribution, but Net::Telnet , for example, is not, and has to be installed separately.

If your perl is installed somewhere other than /usr prefix, you need to edit the script and change '#!/usr/bin/perl' line to the full path to perl binary on your system.

Also, I've noticed you have a trailing ^M behind /usr/bin/perl , which is a CRLF sequence used by text editors on Windows and other editors configured to work in Windows mode. I don't know how you got it there, but I assure you it is not present in the original file. One way would be by doing copy&paste of the script's code from browser to some text editor on a Windows machine, in which case I would suggest you either do a proper git clone or download current project as zip.

**Comment by aloudahi** [comment]
goodmorning

there is perl and installed at '/usr/bin/', I execute it on centos7, no problem with this?

thank you so much

**Comment by markomdinic** [comment]
Assuming you have Net::Telnet module installed (yum install perl-Net-Telnet) and script downloaded via git clone or as ZIP from GitHub, without editing it, pasting it from web, etc. -  there should be no problems. Please note that this script uses telnet to log in to network devices, so you need to have telnet access enabled and allowed from your centos box on those devices.
